version: 2  # RTD configuration version
build:
  os: ubuntu-22.04  # Operating system for the build (default: ubuntu-20.04)
  tools:
    python: "3.10"  # Python version for the build environment

sphinx:
  configuration: docs/source/conf.py  # Path to the Sphinx `conf.py` file
