version: 2  # RTD configuration version
build:
  os: ubuntu-22.04  # Operating system for the build (default: ubuntu-20.04)
  tools:
    python: "3.10"  # Python version for the build environment

python:
  install:
    - requirements: requirements.txt  # Ensure dependencies are installed from this file

sphinx:
  configuration: docs/source/conf.py  # Path to the Sphinx `conf.py` file
